M48
; DRILL file KiCad 10.0.4 date 2026-08-18T20:37:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-18T20:37:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X319.1Y-52.84
X334.1Y-52.84
T2
X94.0Y-225.2
X94.6Y-48.6
X290.9Y-225.2
X301.8Y-48.6
M30
